#!/bin/bash

echo "🧹 Starting cleanup of empty and unnecessary files..."

# Remove empty markdown documentation files
echo "📄 Removing empty markdown files..."
rm -f "SITE_STATUS_WORKING.md"
rm -f "HERO_BACKGROUND_AND_COLOR_SCHEME_UPDATE_COMPLETE.md"
rm -f "TESTIMONIALS_CAROUSEL_FIX.md"
rm -f "ADVANCED_OPTIMIZATIONS_RESTORATION_COMPLETE.md"
rm -f "DOMAIN_CONFIGURATION_GUIDE.md"
rm -f "NAVIGATION_FIX_COMPLETE.md"
rm -f "ADVANCED_FEATURES_IMPLEMENTATION_COMPLETE.md"
rm -f "STRIPE_ENVIRONMENT_FIX_COMPLETE_SAFE.md"
rm -f "ASSESSMENT_ERROR_FIX_COMPLETE.md"
rm -f "FINAL_IMPLEMENTATION_STATUS_COMPLETE.md"
rm -f "FINAL_DEPLOYMENT_STATUS.md"
rm -f "FINAL_DEPLOYMENT_SUMMARY.md"
rm -f "COLOR_SCHEME_LAYOUT_ENHANCEMENT_COMPLETE.md"
rm -f "ADVANCED_FEATURES_PHASE_3_COMPLETE.md"
rm -f "ASSESSMENT_ERROR_FIX_VERIFICATION.md"
rm -f "WEBSITE_FIX_COMPLETE.md"
rm -f "COMPONENT_IMPROVEMENTS_COMPLETE.md"
rm -f "MODERN_REDESIGN_PROGRESS.md"
rm -f "COMPREHENSIVE_UPDATES_COMPLETE.md"
rm -f "NAVIGATION_UI_IMPROVEMENT_COMPLETE.md"
rm -f "HOMEPAGE_STATS_REMOVAL_COMPLETE.md"
rm -f "ASSESSMENT_FINAL_FIX_CONFIRMED.md"
rm -f "PRODUCTION_DEPLOYMENT_SUCCESS.md"
rm -f "ASSESSMENT_ERROR_FINAL_RESOLUTION.md"
rm -f "IMAGE_AND_READABILITY_UPDATES.md"
rm -f "HIGHER_EDUCATION_NONPROFIT_MESSAGING_COMPLETE.md"
rm -f "PRODUCTION_DEPLOYMENT_CHECKLIST.md"
rm -f "DEPLOYMENT_NOTES.md"
rm -f "IMAGE_OVERLAY_CONTRAST_FIX_COMPLETE.md"
rm -f "MODERN_REDESIGN_COMPLETE.md"
rm -f "COMPREHENSIVE_ENHANCEMENT_IMPLEMENTATION_COMPLETE.md"
rm -f "FINAL_OPERATIONAL_STATUS.md"
rm -f "DYNAMIC_CONTENT_FIX_COMPLETE.md"
rm -f "HOMEPAGE_HERO_BACKGROUND_COMPLETE.md"
rm -f "LANGUAGEPROVIDER_ERROR_RESOLUTION_COMPLETE.md"
rm -f "FOOTER_CONTENT_REMOVAL_COMPLETE.md"

# Remove empty test files
echo "🧪 Removing empty test files..."
rm -f "test-survey-error.js"
rm -f "test-dynamic-content.js"
rm -f "test-url-flow.js"

# Remove empty demo pages
echo "🎭 Removing empty demo pages..."
rm -f "app/page.simple.tsx"
rm -f "app/component-showcase/page.tsx"
rm -f "app/hero-test/page.tsx"
rm -f "app/layout.simple.tsx"
rm -f "app/test-navbars/page.tsx"
rm -f "app/survey/page-new.tsx"
rm -f "app/survey/page-improved.tsx"
rm -f "app/survey/page_new.tsx"
rm -f "app/survey/page-original.tsx"
rm -f "app/survey/page_old.tsx"

# Remove entire empty demo directories
echo "📁 Removing empty demo directories..."
rm -rf "app/demos/form-gallery"
rm -rf "app/demos/enhanced-form"
rm -rf "app/demos/loading-states"
rm -rf "app/demos/accessibility-demo"
rm -rf "app/demos/responsive-demo"
rm -rf "app/demos/testimonials-carousel"
rm -rf "app/demos/card-gallery"
rm -rf "app/demos/onboarding-tour-demo"

# Remove empty component files
echo "⚛️ Removing empty/unused component files..."
rm -f "components/PageHero.tsx"
rm -f "components/Hero.tsx"
rm -f "components/ui/loading-states.tsx"
rm -f "components/Navbar.tsx"
rm -f "components/advanced/AdvancedOptimizations.tsx"
rm -f "components/payments/QuickCheckout.tsx"
rm -f "components/client-wrappers/ClientLink.tsx"
rm -f "components/client-wrappers/SafeLink.tsx"
rm -f "components/forms/MultiStepForm.tsx"
rm -f "components/analysis/BundleAnalysisComponents.tsx"
rm -f "components/patterns/AdvancedPatterns.tsx"
rm -f "components/ab-testing/ABTestDashboard.tsx"
rm -f "components/ab-testing/ABTestComponents.tsx"
rm -f "components/HowItWorks.tsx"
rm -f "components/ClientOptimizations.tsx"
rm -f "components/Contact.tsx"
rm -f "components/providers/AnalyticsProvider.tsx"
rm -f "components/providers/ThemeProvider.tsx"
rm -f "components/providers/QueryProvider.tsx"
rm -f "components/Services.tsx"
rm -f "components/charts/EnhancedChart.tsx"
rm -f "components/Hero-broken.tsx"
rm -f "components/three/ThreeComponents.tsx"
rm -f "components/CallToAction-clean.tsx"
rm -f "components/Footer.tsx"
rm -f "components/Testimonials.tsx"
rm -f "components/realtime/RealTimeComponents.tsx"
rm -f "components/testing/QualityAssurance.tsx"
rm -f "components/results/AIAnalysisResults.tsx"
rm -f "components/SectionExplanation.tsx"
rm -f "components/StatsSection.tsx"
rm -f "components/pwa/PWAInstall.tsx"
rm -f "components/CallToAction.tsx"
rm -f "components/cookie-consent/CookieConsentBanner.tsx"
rm -f "components/StatsBanner.tsx"
rm -f "components/Hero_old.tsx"
rm -f "components/modern/ModernHero-old.tsx"
rm -f "components/modern/ImprovedModernContactFixed.tsx"
rm -f "components/modern/ModernContact.tsx"
rm -f "components/modern/ModernAbout.tsx"
rm -f "components/modern/ModernHero.tsx"
rm -f "components/modern/ValueProposition.tsx"
rm -f "components/modern/ModernHero-new.tsx"
rm -f "components/TestimonialsCarousel.tsx"
rm -f "components/performance/PerformanceOptimizations.tsx"
rm -f "components/performance/PerformanceComponents.tsx"
rm -f "components/seo/PerformanceHeadScript.tsx"
rm -f "components/seo/EnhancedSEO.tsx"
rm -f "components/seo/SEOProvider.tsx"
rm -f "components/seo/StructuredData.tsx"
rm -f "components/seo/MetaTags.tsx"
rm -f "components/seo/ReadProgress.tsx"
rm -f "components/seo/DynamicSEO.tsx"
rm -f "components/effects/WebGLEffects.tsx"
rm -f "components/accessibility/AccessibilityComponents.tsx"
rm -f "components/accessibility/AccessibilityEnhancements.tsx"
rm -f "components/CallToAction-fixed.tsx"
rm -f "components/animations/GSAPAnimations.tsx"
rm -f "components/animations/GSAPComponents.tsx"
rm -f "components/About.tsx"
rm -f "components/analytics/DataVisualization.tsx"
rm -f "components/Hero_Fixed.tsx"

# Remove empty lib files
echo "📚 Removing empty lib files..."
rm -f "lib/analysis/bundle-analyzer.ts"
rm -f "lib/cache/redis-cache.ts"
rm -f "lib/scoring-algorithm.ts"
rm -f "lib/offline-storage.ts"
rm -f "lib/three/webgl-manager.ts"
rm -f "lib/realtime/websocket-server.ts"
rm -f "lib/accessibility/accessibility-manager.ts"
rm -f "lib/animations/gsap-animations.ts"
rm -f "lib/ab-testing.ts"

# Remove empty validation scripts
echo "🔧 Removing empty validation scripts..."
rm -f "validate-advanced-optimizations.sh"
rm -f "validate-implementation.sh"
rm -f "test-languageprovider-fix.sh"

# Remove empty prisma seed file
echo "🌱 Removing empty prisma seed..."
rm -f "prisma/seed.ts"

# Clean up empty directories
echo "🗂️ Removing empty directories..."
find . -type d -empty -delete 2>/dev/null || true

echo "✅ Cleanup complete! Removed all empty and unnecessary files."
echo "📊 Files remaining:"
find . -name "*.tsx" -o -name "*.ts" -o -name "*.js" -o -name "*.jsx" | grep -v node_modules | wc -l
