name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1.  Grab the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2.  Set up Node + pnpm cache
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 3.  Install deps
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4.  Type-check & lint
      - name: Type-check
        run: pnpm exec tsc --noEmit
      - name: ESLint
        run: pnpm run lint